[package]
name = "redact-env-logger"
version = "0.1.0"
authors = ["Elad Kaplan <kaplan.elad@gmail.com>"]
edition = "2021"

[workspace]

[dependencies]
text-redaction = {path = "../../../"}
log = "0.4.0"
env_logger = "0.9.0"
regex = "1.6.0"
